name: VMB build

on:
  push:
    branches: [ "master" , "ci-test" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_n_release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:

      - name: get redist
        run: |
          Invoke-WebRequest -URI https://download.microsoft.com/download/1/6/5/165255E7-1014-4D0A-B094-B6A430A6BFFC/vcredist_x64.exe -Outfile vcredist_x64.exe
      
      - name: install redist
        run: |
          7z e -ix64 vcredist_x864.exe
          Start-Process -FilePath "x64\Setup.exe" -ArgumentList "/passive" -Wait -Passthru;
          
      - name: Download VMB Release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "Vermintide-Mod-Framework/Vermintide-Mod-Builder"
          latest: true
          fileName: "vmb-1.8.2.zip"
          zipBall: true

      - name: Extract VMB
        run: 7z x vmb-1.8.2.zip -aou

      - uses: suisei-cn/actions-download-file@v1.3.0
        id: SDK  # Remember to give an ID if you need the output filename
        name: Download the file
        with:
          url: "https://cdn.jsdelivr.net/npm/workbox-sw@5.1.3/build/workbox-sw.min.js"
          target: public/

      - name: Setup Dirs
        run: |
          New-Item -ItemType Directory -Force -Path "mods/.temp"
          New-Item -ItemType Directory -Force -Path "mods/loremasters-armoury"
          New-Item -ItemType Directory -Force -Path "workshop/content/552500/2789506353"
          New-Item -ItemType Directory -Force -Path "VT2-SDK" 

      - name: Checkout SDK
        uses: actions/checkout@v3
        with:
          repository: dalokraff/Vermintide-Mod-Builder
          ref: ci-test
          path: sdk
          sparse-checkout: ''

      - name: Extract SDK
        run: |
          7z x sdk/VT2-SDK.zip

      - name: Copy .vmbrc
        run: |
          .\vmb.exe config
          Copy-Item "sdk\.vmbrc" -Destination ".vmbrc"
          
                        
      - name: Check VMB
        run: |
          .\vmb.exe --version

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: mods/loremasters-armoury
          sparse-checkout: ''
          
      - name: Build Mod
        run: |
          .\vmb.exe build loremasters-armoury --verbose
          exit 0

      - name: Build Mod
        run: |
          cd mods/.temp/
          ls
      
